'use strict';

// In-app self-update mechanics (the pieces that are testable on any OS):
//
//   resolveInstallDir  where the running Fleet lives (node.exe sits in the
//                      install folder next to Fleet.exe)
//   buildApplyScript   the hidden PowerShell applier that runs AFTER Fleet
//                      quits: it mirrors the staged new version over the
//                      install folder, syncs Add/Remove Programs, and
//                      relaunches Fleet
//   applyUpdate        writes the applier and starts it detached
//
// The flow is deliberately installer-free: the updater downloads the
// portable zip, verifies its digest, stages it, then swaps files while the
// app is closed. No second window, no wizard, nothing to click.

const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');
const unzip = require('./unzip');

function resolveInstallDir(execPath) {
  const dir = path.dirname(String(execPath || ''));
  if (!dir) return { ok: false, error: 'Could not determine the install folder.' };
  const exe = path.join(dir, 'Fleet.exe');
  if (!fs.existsSync(exe)) {
    return {
      ok: false,
      error: 'Automatic updates only work in an installed (or portable) copy of Fleet - this build runs from a development folder.',
    };
  }
  return { ok: true, dir };
}

/** The applier. Plain Windows PowerShell 5.1 (always present), run hidden. */
function buildApplyScript(opts) {
  const options = opts || {};
  const waitPids = `@(${Number(options.appPid) || 0}, ${Number(options.nodePid) || 0})`;
  return [
    '# Fleet self-update applier - generated by the updater. Safe to delete.',
    'param(',
    '  [string]$InstallDir,',
    '  [string]$StageDir,',
    '  [string]$UpdatesDir,',
    '  [int]$AppPid,',
    '  [int]$NodePid,',
    '  [string]$Version',
    ')',
    '$ErrorActionPreference = \'Continue\'',
    "$log = Join-Path $env:TEMP 'FleetUpdate.log'",
    'function Log($m) { try { Add-Content -Path $log -Value ("[{0}] {1}" -f (Get-Date -Format s), $m) } catch {} }',
    'Log ("apply-update start: v" + $Version + " -> " + $InstallDir)',
    '',
    '# 1. Wait for the running Fleet and its backend to exit (graceful, then forced).',
    `$pids = ${waitPids}`,
    'foreach ($p in $pids) {',
    '  if ($p -le 0) { continue }',
    '  try {',
    '    $proc = Get-Process -Id $p -ErrorAction SilentlyContinue',
    '    if ($proc) { Log ("waiting for pid " + $p); $proc | Wait-Process -Timeout 45 -ErrorAction SilentlyContinue }',
    '  } catch {}',
    '  try { Stop-Process -Id $p -Force -ErrorAction SilentlyContinue } catch {}',
    '}',
    '# Safety net: any Fleet/node process still running from the install folder.',
    '$fleetExe = Join-Path $InstallDir \'Fleet.exe\'',
    'foreach ($name in @(\'Fleet\', \'node\')) {',
    '  try {',
    '    Get-Process -Name $name -ErrorAction SilentlyContinue |',
    '      Where-Object { $_.Path -and $_.Path.StartsWith($InstallDir, [StringComparison]::OrdinalIgnoreCase) } |',
    '      ForEach-Object { Log ("closing stray " + $name + " pid " + $_.Id); Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue }',
    '  } catch {}',
    '}',
    'Start-Sleep -Milliseconds 800   # let Windows release the file locks',
    '',
    '# 2. Mirror the staged new version over the install folder. /MIR removes',
    '#    files that only existed in older versions; the uninstaller is kept.',
    '$null = robocopy $StageDir $InstallDir /MIR /XF uninstall.exe /R:2 /W:1 /NFL /NDL /NJH /NJS /NP',
    'if ($LASTEXITCODE -ge 8) { Log ("robocopy failed: " + $LASTEXITCODE) } else { Log "robocopy ok" }',
    '',
    '# 3. Keep Add/Remove Programs in sync with the new version.',
    'try {',
    "  $key = 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Fleet'",
    '  if (Test-Path $key) {',
    '    Set-ItemProperty -Path $key -Name DisplayVersion -Value $Version -Type String',
    '    Set-ItemProperty -Path $key -Name InstallLocation -Value $InstallDir -Type String',
    '    $kb = [int]((Get-ChildItem -LiteralPath $InstallDir -Recurse -File -ErrorAction SilentlyContinue | Measure-Object -Property Length -Sum).Sum / 1024)',
    '    Set-ItemProperty -Path $key -Name EstimatedSize -Value $kb -Type DWord',
    '  }',
    '} catch { Log ("registry sync skipped: " + $_) }',
    '',
    '# 4. Relaunch the new version.',
    'try {',
    '  Start-Process -FilePath $fleetExe -WorkingDirectory $InstallDir',
    '  Log \'relaunched\'',
    '} catch { Log ("relaunch failed: " + $_) }',
    '',
    '# 5. Clean up the staged update (best effort - the next update sweeps leftovers).',
    'try { Remove-Item -LiteralPath $UpdatesDir -Recurse -Force -ErrorAction SilentlyContinue } catch {}',
    'Log \'apply-update done\'',
    '',
  ].join('\r\n');
}

/** Unpacks the verified portable zip into `stageDir`, tolerating both zip
 *  layouts (a single "Fleet/" root, or files at the top level) and refusing
 *  anything that does not look like a Fleet distribution. */
function stageZip(zipPath, stageDir) {
  let names;
  try {
    names = unzip.listEntries(zipPath);
  } catch (err) {
    return { ok: false, error: `The downloaded update is not a valid archive: ${err.message}` };
  }
  const files = names.filter(n => !n.endsWith('/') && !n.endsWith('\\'));
  if (!files.length) return { ok: false, error: 'The downloaded update archive is empty.' };
  const normalized = files.map(n => n.replace(/\\/g, '/'));
  const hasRoot = normalized.every(n => n === 'Fleet' || n.startsWith('Fleet/'));
  const strip = hasRoot ? 'Fleet' : null;
  try {
    fs.rmSync(stageDir, { recursive: true, force: true });
    unzip.extractZip(zipPath, stageDir, strip ? { stripRoot: strip } : {});
  } catch (err) {
    return { ok: false, error: `Could not unpack the update: ${err.message}` };
  }
  if (!fs.existsSync(path.join(stageDir, 'Fleet.exe'))) {
    return { ok: false, error: 'The downloaded update does not contain Fleet.exe - it may be a corrupt download. Try again.' };
  }
  return { ok: true, stageDir, strip };
}

/** Writes the applier and launches it detached + hidden.
 *  Returns { ok, pid?, error? }. */
function applyUpdate(opts) {
  const options = opts || {};
  if (process.platform !== 'win32') {
    return { ok: false, error: 'The update applier only runs on Windows.' };
  }
  const installDir = String(options.installDir || '');
  const stageDir = String(options.stageDir || '');
  const updatesDir = String(options.updatesDir || '');
  if (!installDir || !stageDir || !updatesDir) {
    return { ok: false, error: 'The update applier needs the install, staging and updates folders.' };
  }
  const scriptPath = path.join(updatesDir, 'apply-update.ps1');
  const script = buildApplyScript(options);
  try {
    fs.mkdirSync(updatesDir, { recursive: true });
    fs.writeFileSync(scriptPath, script, 'utf8');
  } catch (err) {
    return { ok: false, error: `Could not write the update applier: ${err.message}` };
  }
  const args = [
    '-NoProfile',
    '-ExecutionPolicy', 'Bypass',
    '-File', scriptPath,
    '-InstallDir', installDir,
    '-StageDir', stageDir,
    '-UpdatesDir', updatesDir,
    '-AppPid', String(Number(options.appPid) || 0),
    '-NodePid', String(Number(options.nodePid) || 0),
    '-Version', String(options.version || ''),
  ];
  return new Promise((resolve) => {
    let child;
    try {
      child = spawn('powershell.exe', args, { detached: true, stdio: 'ignore', windowsHide: true });
    } catch (err) {
      resolve({ ok: false, error: `Could not start the update applier: ${err.message}` });
      return;
    }
    let settled = false;
    const done = (result) => { if (!settled) { settled = true; resolve(result); } };
    child.once('error', (err) => done({ ok: false, error: `Could not start the update applier: ${err.message}` }));
    child.once('spawn', () => { child.unref(); done({ ok: true, pid: child.pid }); });
    setTimeout(() => { try { child.unref(); } catch (_) {} done({ ok: true, pid: child.pid }); }, 8000);
  });
}

module.exports = { resolveInstallDir, buildApplyScript, stageZip, applyUpdate, extractZip: unzip.extractZip, listEntries: unzip.listEntries };
